#!/bin/sh
cd executiontests
if test "$1x" = "x"; then
  FILES=`ls *.java`
else
  FILES=$1
fi;

for i in $FILES; do
  echo $i
  java -cp .. GenerateBCodefile $i >/dev/null
  java `basename $i .java` "Test"
done;
cd ..

