#!/bin/sh
cd executiontests
if test "$1x" = "x"; then
  FILES=`ls *.java`
else
  FILES=$1
fi;

for i in $FILES; do
  echo $i
  java -cp .. JavaCompiler -classpath . $i >/dev/null
  java `basename $i .java` 2>&1 | diff -b -B - `basename $i .java`.result
  if test $? -eq 0; then
	  echo "$i passed"
  else
	  echo "$i failed"
  fi
done;
cd ..

