module "java5 frontend", {
	imports "java4 frontend"

	jastadd {
		include "grammar/*"
		include "frontend/*"
		excludeFrom "java4 frontend", "frontend/BytecodeAttributes.jrag"
		excludeFrom "java4 frontend", "frontend/BytecodeDescriptor.jrag"
		excludeFrom "java4 frontend", "frontend/BytecodeReader.jrag"
	}

	scanner {
		excludeFrom "java4 frontend", "scanner/Identifiers.flex"
		include "scanner/Operators.flex"
		include "scanner/Keywords.flex"
		include "scanner/Identifiers.flex", [1]
	}

	parser {
		include "parser/*"
	}
}

